name: Check freepeople

on:
  workflow_dispatch: {}

jobs:
  check-freepeople:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('check_freepeople/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install requirements
        run: python -m pip install -r check_freepeople/requirements.txt
      - name: Check amber list
        run: python check_freepeople/action.py
