name: Check office

on:
  workflow_dispatch: {}

jobs:
  check-office:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install requirements
        run: python3 -m pip install -r check_office/requirements.txt
      - name: Check office
        run: python3 check_office/action.py
