name: Check amber list

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  check-amber-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install requirements
        run: python3 -m pip install -r check_amber_list/requirements.txt
      - name: Check amber list
        run: python3 check_amber_list/action.py
